package com.ameraldo.radar.viewmodel

import android.annotation.SuppressLint
import android.app.Application
import android.content.Context
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.ameraldo.radar.data.AppDatabase
import com.ameraldo.radar.data.LocationError
import com.ameraldo.radar.data.LocationState
import com.ameraldo.radar.data.RecordedPointEntity
import com.ameraldo.radar.service.LocationService
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.launch

/**
 * ViewModel that manages communication with [LocationService].
 *
 * Acts as an intermediary between the UI and the service.
 * Uses a binder connection to access service state flows.
 * When service is not bound, returns default (empty) values to prevent null checks in UI.
 *
 * ## State Properties (delegated to LocationService when bound)
 * - [locationState]: Current GPS location, accuracy, satellites
 * - [isRecording]: Whether a route is being recorded
 * - [isFollowing]: Whether following a saved route
 * - [currentRouteId]: ID of current route (recording or following)
 * - [currentRouteName]: Name of current route
 * - [currentRoutePoints]: Points for current route (from Room)
 * - [followingRemainingPoints]: Points yet to be reached while following
 *
 * ## Methods
 * - [setLocationService]/[clearLocationService]: Bind/unbind from service
 * - [startLocationUpdates]: Request location updates via service
 * - [startRecording]/[stopRecording]: Control route recording
 * - [startFollowing]/[stopFollowing]: Control route following
 * - [saveRoute]/[deleteRoute]: Manage route persistence
 * - [onPermissionDenied]/[onPermissionPermanentlyDenied]: Handle permission errors
 */
class LocationViewModel(application: Application) : AndroidViewModel(application) {
    // Cached default flows for when service is not bound
    // Prevents null checks in UI - just shows empty/loading state
    private val _defaultLocationState = MutableStateFlow(LocationState())
    private val _defaultFalse = MutableStateFlow(false)
    private val _defaultNullLong = MutableStateFlow<Long?>(null)
    private val _defaultNullString = MutableStateFlow<String?>(null)
    private val _defaultEmptyPoints = MutableStateFlow<List<RecordedPointEntity>>(emptyList())

    @SuppressLint("StaticFieldLeak") // ViewModel lifecycle is properly managed, Application context is safe
    private var _locationService: LocationService? = null

    private val database = AppDatabase.getInstance(getApplication())
    private val routeDao = database.routeDao()

    /** Current GPS location state, or default if service not bound */
    val locationState: StateFlow<LocationState>
        get() = _locationService?.locationState ?: _defaultLocationState

    /** Whether recording is active, or false if service not bound */
    val isRecording: StateFlow<Boolean>
        get() = _locationService?.isRecording ?: _defaultFalse

    /** Whether following is active, or false if service not bound */
    val isFollowing: StateFlow<Boolean>
        get() = _locationService?.isFollowing ?: _defaultFalse

    /** Current route ID, or null if service not bound */
    val currentRouteId: StateFlow<Long?>
        get() = _locationService?.currentRouteId ?: _defaultNullLong

    /** Current route name, or null if service not bound */
    val currentRouteName: StateFlow<String?>
        get() = _locationService?.currentRouteName ?: _defaultNullString

    /** Current route points (Room-backed), or empty if service not bound */
    val currentRoutePoints: StateFlow<List<RecordedPointEntity>>
        get() = _locationService?.currentRoutePoints ?: _defaultEmptyPoints

    /** Remaining points to follow, or empty if service not bound */
    val followingRemainingPoints: StateFlow<List<RecordedPointEntity>>
        get() = _locationService?.followingRemainingPoints ?: _defaultEmptyPoints

    /**
     * Sets the LocationService reference after binding.
     * Called by MainActivity after service connection.
     */
    fun setLocationService(service: LocationService) {
        _locationService = service
    }

    /**
     * Clears the LocationService reference.
     * Called when service disconnects or activity unbinds.
     */
    fun clearLocationService() {
        _locationService = null
    }

    private val context: Context
        get() = getApplication<Application>()

    /**
     * Requests location updates from the service.
     * Creates intent and starts the service if not already running.
     */
    fun startLocationUpdates() {
        val intent = LocationService.requestStartLocationUpdates(context)
        context.startService(intent)
    }

    /**
     * Starts recording a new route.
     * Creates intent with empty name (will be auto-generated by service).
     */
    fun startRecording() {
        val intent = LocationService.createStartRecordingIntent(context, "")
        context.startForegroundService(intent)
    }

    /**
     * Stops the current recording.
     *
     * Tries binder first (when activity is bound), falls back to intent
     * (for notification bar stop action when activity is not connected).
     */
    fun stopRecording() {
        _locationService?.stopRecordingViaBinder()
            ?: run {
                // Fallback: service not bound (e.g., notification bar stop when activity is detached)
                val intent = LocationService.createStopRecordingIntent(context)
                context.startService(intent)
            }
    }

    /**
     * Saves the current route with a new name.
     *
     * @param newName New name for the route (null to skip save)
     */
    fun saveRoute(newName: String?) {
        if (newName != null) {
            viewModelScope.launch {
                val routeId = currentRouteId.first() ?: return@launch
                val route = routeDao.getRouteById(routeId) ?: return@launch
                routeDao.updateRoute(route.copy(name = newName))
            }
        }
    }

    /**
     * Deletes the current route and clears related state.
     * Called when user chooses to discard (not save) a recorded route.
     */
    fun deleteRoute() {
        _locationService?.deleteCurrentRoute()
    }

    /**
     * Starts following a saved route.
     *
     * @param routeId ID of the route to follow
     */
    fun startFollowing(routeId: Long) {
        val intent = LocationService.createStartFollowingIntent(context, routeId)
        context.startForegroundService(intent)
    }

    /**
     * Stops following the current route.
     *
     * Tries binder first (when activity is bound), falls back to intent
     * (for notification bar stop action when activity is not connected).
     */
    fun stopFollowing() {
        _locationService?.stopFollowingViaBinder()
            ?: run {
                // Fallback: service not bound (e.g., notification bar stop when activity is detached)
                val intent = LocationService.createStopFollowingIntent(context)
                context.startService(intent)
            }
    }

    /**
     * Sets a permission denied error state in the service.
     * Called when user denies location permission.
     */
    fun onPermissionDenied() {
        _locationService?.setPermissionError(LocationError.PermissionDenied())
    }

    /**
     * Sets a permission permanently denied error state in the service.
     * Called when user checks "Don't ask again".
     */
    fun onPermissionPermanentlyDenied() {
        _locationService?.setPermissionError(LocationError.PermissionDenied(permanentlyDenied = true))
    }
}